### ISSUE TITLE
node_modules is not recognized as an internal or external command

### ISSUE THREAD

**Issue by tainmar** [mpociot/whiteboard#1]
Well done with white board it looks awesome !
Everything was going fine but when I use 'npm start' command I've got the following error.
(nota : first time using node and npm. Windows 10 user)
![image](https://cloud.githubusercontent.com/assets/6144551/12620613/3ba06676-c51d-11e5-90de-95bc73a730ff.png)

**Comment by mpociot** [comment]
That seems to be a windows specific issue.
Please install the `hexo-cli` package globally and run the server with `hexo server` manually.
I'll update the README accordingly.

Thank you for reporting it!

**Comment by tainmar** [comment]
Works like a charm. Thank you :smile:
