### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by bjrmatos** [mpociot/whiteboard#3]
Just wanna say thank you for doing this! i've found about slate a month ago but i don't wanna install ruby in order to use it, so your solution works for me and my team :)

**Comment by mpociot** [comment]
Wow - thank you very much for your kind words.

If you've built an API documentation that is available somewhere publicly let me know! :)

**Comment by bjrmatos** [comment]
of course!! we're in the process right now.. i'll let you know when it is ready :+1:
