### ISSUE TITLE
Blank Index.html

### ISSUE THREAD

**Issue by gunners81** [mpociot/whiteboard#34]
i got blank index.html after do hexo generate / npm run generate
 what should i check ?

**Comment by gunners81** [comment]
problem solved by downgrade node from 14.x to 12.18.x 

thanks for this wonderful app !

**Comment by DishantPal** [comment]
any fix for node 14.x?

**Comment by Zekoner** [comment]
For node 14.x+ solved by run 
`npm audit fix --force`
