### ISSUE TITLE
Icon Font Issues

### ISSUE THREAD

**Issue by mmccook** [mpociot/whiteboard#4]
Just cloned the repo and also noticed on the Demo that none of the icons in the <asides> are displaying, its just a box. 

Errors from the demo: 

> http://www.marcelpociot.com/whiteboard/css/font-icon-path.ttf?v=#font-icon-version Failed to load resource: the server responded with a status of 404 (Not Found)  
> 
> http://www.marcelpociot.com/whiteboard/css/font-icon-path.woff?v=#font-icon-version Failed to load resource: the server responded with a status of 404 (Not Found)

This was tested on latest versions of Chrome and Firefox.

**Comment by mpociot** [comment]
Thanks for pointing it out.
Since I had FontAwesome installed locally on my mac, I missed this error.

I also updated the demo.
