### ISSUE TITLE
Active Code Tab and Code Styling

### ISSUE THREAD

**Issue by ghost** [mpociot/whiteboard#5]
Active Code Tab and Code Styling doesn't work on generated html files. Look image.

Npm install gave error while installing. On windows.

```
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN prefer global marked@0.3.5 should be installed with -g
```

![capture](https://cloud.githubusercontent.com/assets/1254613/12668693/e46741f4-c661-11e5-9fc7-b293879c083b.PNG)

**Comment by mpociot** [comment]
Do you get any output in the chrome dev tools?
The generated HTML looks good. Don't think it's npm related

**Comment by ghost** [comment]
Yes. There is a reference link. Adding **https** fixed the problem. It defaults to **file** protocol on local if not specified. 

`//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.1.0/highlight.min.js`

`https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.1.0/highlight.min.js`
