### ISSUE TITLE
Support for multiple themes

### ISSUE THREAD

**Issue by n-s-k** [mpociot/whiteboard#8]
[That would be great.](https://github.com/evantahler/actionhero/issues/763)

**Comment by mpociot** [comment]
You can already use multiple layout's for different pages.

For example, you could create a new layout file `themes/whiteboard/layout/test.ejs`

Create a new markdown file for your new page, for example: `source/test.md` and modify the Front-Matter of that markdown file, to use the new layout:

``` markdown
---
title: New Page

layout: test
---
# Yay
```

This way, the new generated page `test` will use the `layout/test.ejs` file.

More information can be found at https://hexo.io/docs/templates.html
